server:
  port: 5000

logging:
  level:
    root: INFO
  pattern:
    console: "{\"time\": \"%d{yyyy-MM-dd HH:mm:ss.SSS}\",\"level\": \"%p\",\"PID\": \"${PID:- }\",\"thread\": \"%t\",\"source\": \"%logger{63}:%L\",\"message\": \"%replace(%m%wEx){'[\r\n]+', '\\\\n  '}%nopex\"}%n"

spring:
  application:
    name: "peak-assessment"
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 15000
      leak-detection-threshold: 15000
      minimum-idle: 2
      idle-timeout: 15000
      max-lifetime: 30000
      schema: assessment
    url: ${DB_URL:jdbc:mysql://coding-db.cwj7q2wiuqdl.us-east-1.rds.amazonaws.com:3306/assessment}
    username: ${DB_USERNAME:candidate}
    password: ${DB_PASSWORD:Xzz7ELn1NKQ7}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
